### PR TITLE
Change Maher Colour to New Design

### PR DESCRIPTION
**Pull request by nitro-marky**
Update the current Maher demo front-ends to be reflective of new Maher branding colour. 

  - [x] Maher sidebar to be in shade #0c74bb

**Before**
Screenshot 2022-01-28 at 15 03 32

**After**
Screenshot 2022-01-28 at 17 14 26

### CODE REVIEW

**Review by nitro-marky — COMMENTED** [review]
Old Maher file now deleted

**Review by mattdean-digicatapult — APPROVED** [review]

**Review by dblane-digicatapult — CHANGES_REQUESTED** [review]
no spacing in filenames please

**Review by danielcooperxyz — APPROVED** [review]

**Review by dblane-digicatapult — CHANGES_REQUESTED** [review]
the convention appears to be to use a hyphen rather than underscore.

**Comment by darrylmorton-digicatapult** [comment]
> Old logo left for posterity

I would say delete the old logo, but if anyone else object's then ignore me.

Could you also include a screenshot of the sidebar rollover state please?

**Review by dblane-digicatapult — APPROVED** [review]

**Review by darrylmorton-digicatapult — APPROVED** [review]

**Pull request merged**
